

<form action="agregar" method="POST" class="my-4">
    <div class="row">
        <?php /*
        <div class="col-3">
            <div class="form-group">
                <label>Productos</label>
                <select class="form-control" name="categoria">
                   <?php foreach ($productos as $producto) ?>
                    <tr>
                        <td> 
                            <option value = "<?php $producto->id_categoria ?>"> 
                            <?php echo $producto->categoria ?> </option> 
                        </td>
                    </tr> 
                </select>
            </div>
        </div>
        */ ?>
        <?php /*
        <div class="form-group">
                <label>Producto</label>
                <div class="form-group">
                    <input required name="producto" type="text" class="form-control">
                </div>
        </div>
        */ ?>
        <div class="form-group">
            <label>Marcas</label>
            <select class="form-control" name="marca">
                <tr>
                <?php foreach ($productos as $producto) ?>
                    <td> 
                        <option value = "<?php $producto->marca ?>"> 
                        <?php echo $producto->marca ?> </option> 
                        
                    </td>
                </tr> 
            </select>
        </div>
        <?php /*
        <div class="form-group">
            <label>Precio</label>
            <input required name="precio" type="float" class="form-control">
        </div>
        <div class="form-group">
            <label>Talle</label>
            <input required name="talle" type="float" class="form-control">
        </div>
        */ ?>
    </div>
    <button type="submit" class="btn btn-primary mt-2">Agregar</button>
</form>

