

<form action="agregar" method="POST" class="row g-3 border border-bottom border-primary m-5">
    <div class="col-md-6">
        <label class="form-label">Categoria</label>
        <select class="form-select" name="id_categoria">
            <?php foreach ($categorias as $categoria) : ?>
                <option>
                    <?php echo $categoria->categoria ?>
                </option>                               
            <?php endforeach ?>
        </select>
    </div>
    <div class="col-md-6">
        <label class="form-label">Producto</label>
        <input required name="producto" type="text" class="form-control">
    </div>
    <div class="col-md-6">
        <label class="form-label">Marcas</label>
        <select class="form-select" name="id_marca">
            <?php foreach ($marcas as $marca) : ?>
                <option>
                    <?php echo $marca->marca ?>
                </option>                               
            <?php endforeach ?>
        </select>
    </div>
    <div class="col-md-6">
        <label class="form-label">Precio</label>
        <input required name="precio" type="float" class="form-control">
    </div>
    <div class="col-md-6">
        <label class="form-label">Talle</label>
        <select name="talle" id="talle">
            <option value="35">35</option>
            <option value="35.5">35.5</option>
            <option value="36">36</option>
            <option value="36.5">36.5</option>
            <option value="37">37</option>
            <option value="37.5">37.5</option>
            <option value="38">35</option>
            <option value="38.5">38.5</option>
            <option value="39">39</option>
            <option value="39.5">39.5</option>
            <option value="40">40</option>
            <option value="40.5">40.5</option>
            <option value="41">41</option>
            <option value="41.5">41.5</option>
            <option value="42">42</option>
            <option value="42.5">42.5</option>
            <option value="43">43</option>
            <option value="43.5">43.5</option>
            <option value="44">44</option>
            <option value="44.5">44.5</option>
            <option value="45">45</option>
            <option value="45.5">45.5</option>
            <option value="46">46</option>
        </select>
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary position-absolute end-0">Agregar</button>
    </div>
</form>

