<?php /*
</main>
  <footer class="container-fluid">
    <div class="bg-warning bg-subtle fixed-bottom text-center">
      <address>
        <strong>Shoes Shop SA</strong>
        <br>
          " Libertadores de America 7 "
        <br>
          " Brasil , Rio de Janeiro "
        <br>
        <abbr title="Phone">tel:</abbr>
          " (123) 456-7890 "
      </address>
      <address>
        <strong>Shoes Shop</strong>
        <br>
        <a href="#">ShoeShopTandil@gmail.com</a>
      </address>
    </div>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>