</main>
  <footer class="position-absolute bottom-0">
    <div class="d-flex justify-content-center bg-warning-subtle">
      <p class="text-success">mail de contatcto tumaxlasdudas@gmail.com</p>
    </div>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>