    </main>
    <footer class="container-fluid bg-dark text-light text-center">
      <div class="container">
        <address>
          <strong>Shoes Shop SA</strong>
          <br>
            " Libertadores de America 7 "
          <br>
            " Brasil , Rio de Janeiro "
          <br>
          <abbr title="Phone">tel:</abbr>
            " (123) 456-7890 "
        </address>
        <address>
          <strong>Shoes Shop</strong>
          <br>
          <a href="#">ShoeShopTandil@gmail.com</a>
        </address>
      </div>
    </footer>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script> 
</html>