<form action="agregar" method="POST" class="my-4">
    <div class="row">

        <div class="col-3">
            <div class="form-group">
                <label>Productos</label>
                <select class="form-control">
                    <option>Botines</option>
                    <option>Urbanas</option>
                    <option>Deportivas</option>
                </select>
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>Marcas</label>
                <select class="form-control">
                    <option>Nike</option>
                    <option>Adidas</option>
                    <option>Puma</option>
                    <option>Under Armour</option>
                    <option>DC</option>
                    <option>New Balance</option>
                </select>
            </div>

            <div class="form-group">
                <label>Precio</label>
                <input required name="precio" type="float" class="form-control">
            </div>

            <div class="form-group">
                <label>Talle</label>
                <input required name="talle" type="float" class="form-control">
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary mt-2">Buscar</button>
</form>