<?php require 'templates/header.phtml' ?>

<section id="home"> 
        <div class="container-fluid">
            <div class="row">
                <div class="col text-center">
                    <div class="card" style="width: 18rem;">
                        <img src="..." class="card-img-top" alt="...">
                    <div class="card-body">
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="#pricing" class="btn btn-secondary btn-lg">Buy Now</a>
                    </div>
                </div>
            </div>
        </div>
</section>

<?php require 'templates/footer.phtml' ?>