<?php require './templates/header.phtml' ?>

<section id="ShowByCategoria"> 
    <?php require './templates/carrousel.phtml' ?>
    <div class="container-fluid">
        <div class="row">
            <?php foreach($itemCat as $producto): ?>
                <div class="col-md-4 mb-4 text-center">
                    <div class="card" style="width: 18rem;">
                        <img src="..." class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text"><?= $producto-> Producto ?> (<?= $producto->id_categoria?>)</p>
                        </div>
                    </div>
                </div>
            <?php endforeach ?>
        </div>
    </div>
</section>

<?php require './templates/footer.phtml' ?>